# Change these first
owner: daverad525 # Your GitHub organization or username, where this repository lives
repo: upptime-monitor # The name of this repository

sites:
  - name: A7
    url: https://a7.com.au
  - name: adelaidewebsitedesign.com.au
    url: https://adelaidewebsitedesign.com.au	
  - name: a7 virtual reality tours
    url: https://a7virtualrealitytours.com.au/
  - name: abcfriendssa.net.au
    url: https://abcfriendssa.net.au/
  - name: allclassequipmenttraining.com
    url: https://allclassequipmenttraining.com/
  - name: advancesheetmetal.com.au
    url: https://advancesheetmetal.com.au/
  - name: barossafunerals.com.au
    url: https://barossafunerals.com.au/
  - name: beyond-kathleenstacey.com.au
    url: https://beyond-kathleenstacey.com.au/
  - name: bikeboxes.com.au
    url: https://bikeboxes.com.au/
  - name: blackwoodbusinessdirectory.com.au
    url: https://blackwoodbusinessdirectory.com.au/
  - name: blackwoodtreeservice.com.au
    url: https://blackwoodtreeservice.com.au/
  - name: blmcarchitectural.com.au
    url: https://blmcarchitectural.com.au/
  - name: craigburnwines.com.au
    url: https://craigburnwines.com.au/
  - name: cunninghamandharvey.com.au
    url: https://cunninghamandharvey.com.au/
  - name: emailletterhead.com
    url: https://emailletterhead.com/
  - name: executiveflowers.com.au
    url: https://executiveflowers.com.au/
  - name: families4families.org.au
    url: https://families4families.org.au/
  - name: floorsafe.com.au
    url: https://floorsafe.com.au
  - name: glaciemcooling.com
    url: https://glaciemcooling.com
  - name: hancockandjust.com.au
    url: https://hancockandjust.com.au/
  - name: equiheal.com.au
    url: https://equiheal.com.au/
  - name: hrmmatters.com.au
    url: https://hrmmatters.com.au/
  - name: lisadallarosa.com.au
    url: https://lisadallarosa.com.au/
  - name: mondaymorningmile.com
    url: https://mondaymorningmile.com/
  - name: myoenergy.com.au
    url: https://myoenergy.com.au/
  - name: neatspirits.com.au
    url: https://neatspirits.com.au/
  - name: noarlungacc.org.au
    url: https://noarlungacc.org.au/
  - name: permusoft.com.au
    url: https://permusoft.com.au/
  - name: plantscape.com.au
    url: https://plantscape.com.au/
  - name: redgumandmore.com.au
    url: https://redgumandmore.com.au/
  - name: roofingcentral.com.au
    url: https://roofingcentral.com.au/
  - name: securestart.com.au
    url: https://securestart.com.au/
  - name: sturtstumpcutters.com.au
    url: https://sturtstumpcutters.com.au/
  - name: thechiropracticdomain.com.au
    url: https://thechiropracticdomain.com.au/
  - name: thehillsarborists.com.au
    url: https://thehillsarborists.com.au/
  - name: generaltools.com.au
    url: https://generaltools.com.au/
  - name: bakeandbrew.com.au
    url: https://bakeandbrew.com.au
  - name: voiceoversonthenet.net
    url: https://voiceoversonthenet.net
  - name: Google AU
    url: https://www.google.com.au
  - name: Wikipedia
    url: https://en.wikipedia.org
  - name: Test Broken Site
    url: https://thissitedoesnotexist.koj.co
  - name: IPv6 test
    url: forwardemail.net
    port: 80
    check: "tcp-ping"
    ipv6: true

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /upptime-monitor
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub. A7"
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
